<?php
/**
 * This file is part of EasySwoole-Api.
 *
 * @link     https://www.easyswoole.com
 * @document https://www.easyswoole.com
 * @contact  1592328848@qq.com
 * @license  https://github.com/easy-swoole-api/easyswoole-api/blob/main/LICENSE
 */
declare(strict_types=1);

namespace App\Process;

use EasySwoole\Component\Process\AbstractProcess;

class EchoProcess extends AbstractProcess
{
    protected function run($arg)
    {
        while (true) {
            echo "now is " . date('Y-m-d H:i:s') . "\n";
            sleep(1);
        }
    }

    protected function onException(\Throwable $throwable, ...$args)
    {
        parent::onException($throwable, $args); // TODO: Change the autogenerated stub
    }
}
